//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public cours()
        {
            this.lessons = new HashSet<lesson>();
            this.sections = new HashSet<section>();
            this.usercourses = new HashSet<usercours>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string brief { get; set; }
        public string rate { get; set; }
        public string instructor { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> subCategory { get; set; }
        public string imageFile { get; set; }
        public Nullable<int> lectures { get; set; }
        public Nullable<int> hours { get; set; }
        public string skillLevel { get; set; }
        public string language { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<int> percent { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual subCategory subCategory1 { get; set; }
        public virtual ICollection<lesson> lessons { get; set; }
        public virtual ICollection<section> sections { get; set; }
        public virtual ICollection<usercours> usercourses { get; set; }
    }
}
