//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public profile()
        {
            this.usercourses = new HashSet<usercours>();
            this.userlessons = new HashSet<userlesson>();
        }
    
        public int id { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> admin { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<usercours> usercourses { get; set; }
        public virtual ICollection<userlesson> userlessons { get; set; }
    }
}
