//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        public section()
        {
            this.lessons = new HashSet<lesson>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string brief { get; set; }
        public Nullable<int> completed { get; set; }
        public string description { get; set; }
        public Nullable<int> course { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual ICollection<lesson> lessons { get; set; }
    }
}
