//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subCategory
    {
        public subCategory()
        {
            this.courses = new HashSet<cours>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string classIcon { get; set; }
        public string description { get; set; }
        public Nullable<int> parent { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<cours> courses { get; set; }
    }
}
