//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usercours
    {
        public int courseId { get; set; }
        public int userId { get; set; }
        public Nullable<int> completed { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual profile profile { get; set; }
    }
}
